ALTER TABLE groups ADD COLUMN IF NOT EXISTS location_name TEXT;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS place_id TEXT;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS lon DOUBLE PRECISION;
